conversation_style:
  - "objective"
  - "fast-paced"
  - "enthusiastic"
  - "informative"
roles_person1: "main summarizer"
roles_person2: "questioner/clarifier"
dialogue_structure:
  - "Introduction"
  - "Content"
  - "Conclusion"
podcast_name: "Daily Briefing"
podcast_tagline: "Your Personal Source of Information and Insights"
output_language: "English"
engagement_techniques:
  - "numbers and statistics"
  - "implications"
  - "real-world applications"
  - "thought-provoking analogies"
creativity: 1
user_instructions: ""
max_num_chunks: 8 # maximum number of rounds of discussions in longform
min_chunk_size: 600 # minimum number of characters to generate a round of discussion in longform

text_to_speech:
  default_tts_model: "openai"
  output_directories:
    transcripts: "/tmp/"
    audio: "/tmp/"
  elevenlabs:
    default_voices:
      question: "Chris"
      answer: "Jessica"
    model: "eleven_multilingual_v2"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
    model: "tts-1-hd"
  edge:
    default_voices:
      question: "en-US-JennyNeural"
      answer: "en-US-EricNeural"
  gemini:
    default_voices:
      question: "en-US-Journey-D"
      answer: "en-US-Journey-O"
  geminimulti:
    default_voices:
      question: "R"
      answer: "S"
      model: "en-US-Studio-MultiSpeaker"
  audio_format: "mp3"
  temp_audio_dir: "/tmp/audio/"
  ending_message: "Bye Bye!"
